import type { Metadata } from "next"
import Image from "next/image"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { BookingPopupButton } from "@/components/booking-popup-button"
import { createPageMetadata } from "@/lib/i18n/metadata"
import { buildWhatsAppUrl } from "@/lib/whatsapp"

export const metadata: Metadata = createPageMetadata("spa", "en")
const SPA_MENU_URL = "/docs/brochure-spa-2025.pdf"
export default function EnglishSpaPage() { return <><Header locale="en" /><main><section className="relative h-[70vh] min-h-[500px] flex items-end"><Image src="/images/ayadina/spa-soins-complementaires.jpg" alt="Treatment room at Les Bains d'Ayadina" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" /><div className="relative z-10 container mx-auto px-4 pb-16 text-white"><p className="uppercase tracking-[0.2em] text-sm text-white/80 mb-4">Les Bains d’Ayadina</p><h1 className="font-serif text-5xl md:text-6xl max-w-3xl">A 250 m² spa for hammam rituals, massages and facials.</h1></div></section><section className="py-20"><div className="container mx-auto px-4 grid lg:grid-cols-2 gap-12 items-center"><div><p className="uppercase tracking-[0.2em] text-sm text-muted-foreground mb-4">Well-being</p><h2 className="font-serif text-4xl mb-6">Traditional Moroccan rituals, contemporary care.</h2><p className="text-muted-foreground mb-4">Enjoy traditional hammam, black soap exfoliation, ghassoul wraps, relaxing massages and natural facial treatments by Natus Marrakech.</p><p className="text-muted-foreground mb-8">We recommend booking treatments 24 hours in advance with reception.</p><div className="flex flex-col sm:flex-row gap-3"><a href={buildWhatsAppUrl("Hello, I would like to book a spa treatment at Riad Ayadina.")} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center bg-primary text-primary-foreground px-6 py-3 text-sm uppercase tracking-wider">Book a treatment</a><a href={SPA_MENU_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center border border-border px-6 py-3 text-sm uppercase tracking-wider">French treatment PDF</a></div></div><Image src="/images/ayadina-home/riad-103.jpg" alt="Ayadina hammam and spa" width={900} height={650} className="object-cover w-full" /></div></section></main><Footer locale="en" /></> }
