import type { Metadata } from "next"
import Image from "next/image"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { createPageMetadata } from "@/lib/i18n/metadata"
import { buildWhatsAppUrl } from "@/lib/whatsapp"

export const metadata: Metadata = createPageMetadata("restaurant", "en")
const MENU_URL = "/docs/carte-menus-vins-cocktails-2025.pdf"
export default function EnglishRestaurantPage() { return <><Header locale="en" /><main><section className="relative h-[70vh] min-h-[500px] flex items-end"><Image src="/images/ayadina/restaurant-table-patio-01.jpg" alt="Restaurant table in the Riad Ayadina patio" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" /><div className="relative z-10 container mx-auto px-4 pb-16 text-white"><p className="uppercase tracking-[0.2em] text-sm text-white/80 mb-4">Restaurant & licensed bar</p><h1 className="font-serif text-5xl md:text-6xl max-w-3xl">French-Moroccan dining in the calm of the riad.</h1></div></section><section className="py-20"><div className="container mx-auto px-4 grid lg:grid-cols-2 gap-12 items-center"><div><p className="uppercase tracking-[0.2em] text-sm text-muted-foreground mb-4">Dining</p><h2 className="font-serif text-4xl mb-6">Patio lunches, rooftop dinners and a rare licensed bar.</h2><p className="text-muted-foreground mb-4">The restaurant serves Moroccan and French classics, seasonal produce, wines, cocktails and cigars in a quiet riad setting.</p><p className="text-muted-foreground mb-8">Open to hotel guests and outside visitors. Dinner reservations are recommended.</p><div className="flex flex-col sm:flex-row gap-3"><a href={buildWhatsAppUrl("Hello, I would like to book a table at Riad Ayadina restaurant.")} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center bg-primary text-primary-foreground px-6 py-3 text-sm uppercase tracking-wider">Book a table</a><a href={MENU_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center border border-border px-6 py-3 text-sm uppercase tracking-wider">French menu PDF</a></div></div><Image src="/images/ayadina/restaurant-bar-01.jpg" alt="Licensed bar at Riad Ayadina" width={900} height={650} className="object-cover w-full" /></div></section></main><Footer locale="en" /></> }
