import type { Metadata } from "next"
import Image from "next/image"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { BookingPopupButton } from "@/components/booking-popup-button"
import { TestimonialsSection } from "@/components/testimonials-section"
import { createPageMetadata } from "@/lib/i18n/metadata"

export const metadata: Metadata = createPageMetadata("rooms", "en")

const rooms = [{ title: "Superior Double Rooms", size: "17 to 22 m²", image: "/images/ayadina/chambres-suites/chambres/01-aida-chambre-02.jpg", text: "Three intimate rooms with Moroccan craft details, private bathroom, reversible air conditioning and breakfast included." }, { title: "Junior Suites", size: "24 to 36 m²", image: "/images/ayadina/chambres-suites/suites/01-ahisia-chambre-03.jpg", text: "Six spacious suites with a private sitting area, generous comfort and the calm rhythm of the riad." }]
export default function EnglishRoomsPage() { return <><Header locale="en" /><main><section className="relative h-[65vh] min-h-[460px] flex items-end"><Image src="/images/ayadina/rooms-hero-adelina-chambre-04.jpg" alt="Room at Riad Ayadina" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" /><div className="relative z-10 container mx-auto px-4 pb-16 text-white"><p className="uppercase tracking-[0.2em] text-sm text-white/80 mb-4">Rooms & suites</p><h1 className="font-serif text-5xl md:text-6xl max-w-3xl">Nine rooms, nine atmospheres.</h1><p className="text-lg max-w-xl mt-4">Superior Double Rooms and Junior Suites, all with breakfast included.</p></div></section><section className="py-20"><div className="container mx-auto px-4 grid md:grid-cols-2 gap-8">{rooms.map((room) => <article key={room.title} className="bg-card border border-border/50"><Image src={room.image} alt={room.title} width={900} height={650} className="h-80 w-full object-cover" /><div className="p-8"><p className="uppercase tracking-[0.2em] text-sm text-muted-foreground mb-3">{room.size}</p><h2 className="font-serif text-3xl mb-4">{room.title}</h2><p className="text-muted-foreground mb-6">{room.text}</p><ul className="text-sm text-muted-foreground space-y-2 mb-8"><li>• Private bathroom</li><li>• Reversible air conditioning</li><li>• High-speed Wi‑Fi</li><li>• Safe</li><li>• Breakfast included</li></ul><BookingPopupButton>Book direct</BookingPopupButton></div></article>)}</div></section><TestimonialsSection locale="en" /></main><Footer locale="en" /></> }
